### ISSUE TITLE
地图左下角添加图例

### ISSUE THREAD

**Issue by gwentmaster** [gwentmaster/StationBuildDoc#1]
![地图图例](https://user-images.githubusercontent.com/49828635/86551972-30450880-bf79-11ea-8aed-85e60a5cc7df.png)

**Comment by gwentmaster** [comment]
在地图左下添加上述图例, 可以做成下面这种, 鼠标停靠后展示
以不同图标来区别集中站与路边站, 以不同颜色来区别规划站与投运站等
![地图弹出框](https://user-images.githubusercontent.com/49828635/86552074-81ed9300-bf79-11ea-986d-1c23f64d8d46.jpg)

**Comment by gwentmaster** [comment]
颜色随意, 图标样式最好不要像示例一样用三角形圆形之类的

**Comment by gwentmaster** [comment]
不同颜色的线路指代的意义也加里面, 如下所示
https://wx2.sbimg.cn/2020/07/06/CMYZA.png

**Comment by gwentmaster** [comment]
补图, 地图图例
https://sbimg.cn/image/CZyWM

**Comment by zxloading** [comment]
ok
