### ISSUE TITLE
地图弹出框添加指定邻近站范围的功能

### ISSUE THREAD

**Issue by gwentmaster** [gwentmaster/StationBuildDoc#12]
接口文档变化在 #11 中
即三个/api/v1/XXX/select/接口都新增一个可选的参数distance, 通过此参数来指定邻近站的范围

**Comment by gwentmaster** [comment]
https://s1.ax1x.com/2020/07/21/UIuRC8.png
效果类似上图, 可以放到其他地方, 也可以采用其他形式, 变化范围在1~5km, 幅度为0.5km即可
https://wx1.sbimg.cn/2020/07/21/DMf2m.png

**Comment by zxloading** [comment]
完成
